-- Messages Table (for real-time chat)
create table if not exists messages (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  user_email text,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS Policies
alter table messages enable row level security;

-- Policy to allow authenticated users to read messages
create policy "Authenticated users can view messages"
  on messages for select
  using ( auth.role() = 'authenticated' );

-- Policy to allow authenticated users to insert their own messages
create policy "Authenticated users can insert messages"
  on messages for insert
  with check ( auth.uid() = user_id );
